---
# ------------------------------------------------------------------------
# tasks file for reboot
# ------------------------------------------------------------------------

- name: check for needs-restarting for debian
  stat:
    path: /var/run/needs-restarting
  register: reboot_check_for_needs_restarting_for_debian

- name: reboot the machine
  shell: "(sleep {{ reboot_delay }} && {{ reboot_command }} &)"
  async: 1
  poll: 0
  ignore_errors: true
  when:
    - ansible_virtualization_type != "docker"
    - needsrestarting.rc == 1 or
      reboot_check_for_needs_restarting_for_debian.stat.exists or
      reboot_force
  notify:
    - 1 wait for the start of reboot
    - 2 wait for the machine to be up
    - 3 gather facts after reboot

- name: flush handlers
  meta: flush_handlers
