---
# ------------------------------------------------------------------------
# handlers file for reboot
# ------------------------------------------------------------------------

- name: 1 wait for the start of reboot
  pause:
    seconds: "{{ reboot_delay }}"
  when:
    - ansible_virtualization_type != "docker"

- name: 2 wait for the machine to be up
  wait_for_connection:
    delay: "{{ reboot_up_delay }}"
  when:
    - ansible_virtualization_type != "docker"

- name: 3 gather facts after reboot
  setup:
  when:
    - ansible_virtualization_type != "docker"
